version: "3"

vars:
  SERVER: firu.dev
  REMOTE_DIR: /srv/www/firu.dev

tasks:
  upload:
    desc: Upload site to server
    cmds:
      - >
        rsync -avz --delete
        --exclude ".git"
        --exclude ".DS_Store"
        --exclude "taskfile.yaml"
        ./
        {{.SERVER}}:{{.REMOTE_DIR}}/

  dev:
    desc: Run file-server
    cmd: python -m http.server 8080
